package com.bookface.repository;

// Generated 02-Mar-2015 16:57:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name = "likes", catalog = "bookface")
public class Likes implements java.io.Serializable {

	private Integer idLikes;
	private Book book;
	private User user;

	public Likes() {
	}

	public Likes(Book book, User user) {
		this.book = book;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_likes", unique = true, nullable = false)
	public Integer getIdLikes() {
		return this.idLikes;
	}

	public void setIdLikes(Integer idLikes) {
		this.idLikes = idLikes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_book")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
