package com.bookface.repository;

// Generated 21-Mar-2015 15:50:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name = "likes")
public class Likes implements java.io.Serializable {

	private Integer idLikes;
	private Book book;
	private Users users;

	public Likes() {
	}

	public Likes(Book book, Users users) {
		this.book = book;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_likes", unique = true, nullable = false)
	public Integer getIdLikes() {
		return this.idLikes;
	}

	public void setIdLikes(Integer idLikes) {
		this.idLikes = idLikes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_book")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
